---
vector_version: "0.36.0"

vector_rpm_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"

vector_config_dir: "/etc/vector"
vector_config_file: "/etc/vector/vector.yaml"
